#ifndef XMLRPC_C_VERSION_INCLUDED 
#define XMLRPC_C_VERSION_INCLUDED 
/* generated by Windows/mkvers.bat on Sun 06/11/2016 ... */ 
#define XMLRPC_C_VERSION "1.39.11" 
#define XMLRPC_VERSION_MAJOR 1 
#define XMLRPC_VERSION_MINOR 39 
#define XMLRPC_VERSION_POINT 11 
#endif 
